### PR TITLE
add my pet to pets.js JSON

### PR DESCRIPTION
**Pull request by danilogila**

### CODE REVIEW

**Review by danilogila — COMMENTED** [review]
adding my pet to pets.js JSON

**Review by danilogila — COMMENTED** [review]
add my pet and fixing space style

**Review by danilogila — COMMENTED** [review]
Fixing space style and add my pet

**Review by danilogila — COMMENTED** [review]
Fixing space style and add my pet

**Comment by vspedr** [comment]
Hi @danilogila, thanks for your contribution!

**Pull request merged**
